### PR TITLE
Milestone 2: Add friendship functionality

### PR DESCRIPTION
**Pull request by wintan1418**
-Create a model with associations and all requested features for friendships.
-implemented all requirements for mileston-2

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
## Hello @wintan1418   :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed this milestone, however I am marking this code review request because of the following reason:

- [ ] The submitted pull request is violating git/github flow we use at [microverse](https://github.com/microverseinc), this pull request is pointing to the master branch wereas it should be pointing to the development branch
- [ ] The submitted pull request contains the failing linters,
- [ ] Try to make this pull request's title a bit descriptive, you can try something like: `milestone 1: Add friendship version 1`

# :point_right: Kindly, fix all of those listed issues and submit another code review request

Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by wintan1418** [comment]
thanks i have implemented it and sent another pull request

**Review by oloomoses — CHANGES_REQUESTED** [review]
Hello team, you have done a great job so far :muscle: 

### Highlights
- well done on the linter configuration :100: 
- Well done on the pull request :clap: 
### To improve
- [ ] Kindly include the authors in the readme to make it more descriptive
- [ ] The app breaks when the signup button is clicked. Kindly fix this.
- [ ] A user should be able to invite friends as per the [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png). Kindly add a button for sending friend requests beside the username.
- [ ] User should be able to accept a request to start a friendship or reject a request. Kindly add buttons to reject and accept friendship beside the username who is receiving the request as per the [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png)
- [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Kindly add unit and integration test for the app  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

Kindly implement the above changes before submitting another review.
**Feel free to reach me on slack or leave a comment while mentioning me and I will be happy to reply**

_Slack: Oloo Moses_

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:wrench::hammer::full_moon:
**Hi Juwon!
Great job so far:clap::clap:. Thank you for implementing some of the changes requested by the last reviewer. However, we still need to make a few changes to get the project approved:muscle:**.

**To improve**

- [ ] There is a button to invite user to friendship on users list page and on single user page (
[screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Make them buttons, Instead of a link.

- [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, the post timeline includes post from every logged-in users. Instead of the current user and his/her friends. Kindly fix this.

- [ ] Currently, there are no tests written for the implemented features in this milestone. Kindly include both unit and integration tests that cover both positive and negative test case scenarios.

**Optional**
- [ ] Move the logic in `application.html.erb` under layout and `_user.html.erb` under `user` in view to a helper. We shouldn't leave logic in our view. Views are only meant to present the information that became available to them from its corresponding controller. And not for generating it.


Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work making the required changes. I was able to authenticate and create a post. Also users who are not my friends could not see my posts. Well done!
Let's make some changes to this PR.
- [ ] fix the failing linter errors
- [ ] I could not send a friend request. I got this error.
review
- [ ] I couldn't also run the tests. I got this error: `ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: main.friends`


### Martin Afani
#### Slack: whiz25

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Good job making the requested changes. I was able to run tests successfully and also send friend request to other users.
Let's however, make some changes before merging this PR.
- [ ] You have some failing test cases.
review
- [ ] The `inverted_friendship` feature doesn't quite work as expected. When my friend request is confirmed, I see the other person as a friend in my list of friends but they don't see me as friend. Instead they see the button for sending a request to me. Please fix that.
- [ ] Add integration tests. An example of an integration test is testing the user flow through the app like signing a user up, creating a post, sending a friend request, etc.



### Martin Afani
#### Slack: whiz25

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello there @wintan1418 you have made such great progress in your milestone, you deserve a 👏🏾 Below is my summary of this PR ⬇️ 

### Highlights

- [ ] Your inverse friendship now works correctly ✔️ 
- [ ] You do not have failing tests ✔️ 

### To Improve

- [ ] Once a friendship is accepted, the confirm or reject buttons are still there. This should not be the case. KIndly work on it.

image

That's all :smile: kindly submit another review when done.

_If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me @mimipeshy. I will be happy to help_
Regards
Peris Ndanu

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👯 

Hello @wintan1418 👋🏾 👋🏾 , congratulations on all the efforts you have made in this milestone. Great job on working on the comments given, the buttons now work as expected 👏🏾  With that, I approve of this project. Go ahead and merge. All the best in the next milestone :technologist:

Regards
Peris Ndanu

**Pull request merged**
